---
test:
  printer_id: 0
  item: test
  cups_alias: laserjet_1102w
  is_active: true
  virgin_access: false
  gcp_xmpp_jid: 345e29425516857a8c70581f58a180c7@cloudprint.googleusercontent.com
  gcp_confirmation_url: https://www.google.com/cloudprint/regconfirmpage?printername=gcp_test_printer&email=dsanderson77@gmail.com&dpi=300&pagesize=215900,279400
  gcp_owner_email: dsanderson77@gmail.com
  gcp_printer_name: gcp_test_printer
  gcp_printerid: d0510370-f36b-356f-1a82-f93c0756a5d9
  gcp_access_token: ya29.pwDUgBLMV17SttR1xdAvnOdbgYhWppYqk072Fhk71AY4VxEU0IFLwbjw
  gcp_refresh_token: 1/MPXAGbW_0AkF5eSFtc96PesWp68lFnOz-HUSUd5aU_w
  gcp_token_type: Bearer
  gcp_token_expiry_time: 2014-10-22 21:59:46.228366920 -07:00
  capability_ppd: /etc/cups/ppd/laserjet_1102w.ppd
  capability_cdd: /etc/cups/cdd/laserjet_1102w.cdd
  gcp_uuid: VND3R11877
  gcp_manufacturer: Hewlett-Packard
  gcp_model: LaserJet P1102w
  gcp_setup_url: http://www8.hp.com/us/en/campaigns/wireless-printing-center/printer-setup-help.html
  gcp_support_url: http://h10025.www1.hp.com/ewfrf/wc/product?product=4110396&lc=en&cc=us&dlc=en&lang=en&cc=us
  gcp_update_url: http://h10025.www1.hp.com/ewfrf/wc/product?product=4110396&lc=en&cc=us&dlc=en&lang=en&cc=us
  gcp_firmware: '20130703'
wild:
  gcp_xmpp_jid: 9bd529179dfa665930799067d4016e9e@cloudprint.googleusercontent.com
  gcp_confirmation_url: https://www.google.com/cloudprint/regconfirmpage?printername=gcp_wild_printer&email=conjugalis@gmail.com&dpi=300&pagesize=215900,279400
  gcp_owner_email: conjugalis@gmail.com
  gcp_printer_name: gcp_wild_printer
  gcp_printerid: 94f42964-2269-fdeb-99af-4ed1bd3f07fe
  gcp_access_token: ya29.hABKAR8kZeUq4vbgUgxV_xv3oXY-cc-FRkZvTvrf5H3fGuklzY6h8s29
  gcp_refresh_token: 1/JDe8Y-rjbxRDzswmLEDuh8CJdnQ40Q10QhRyNWhyHn0
  gcp_token_type: Bearer
  gcp_token_expiry_time: 2014-09-17 19:11:40.886171387 -07:00
  is_active: false
  virgin_access: true
  printer_id: 0
  item: wild
  cups_alias: laserjet_1102w
  capability_ppd: /etc/cups/ppd/laserjet_1102w.ppd
  capability_cdd: /etc/cups/cdd/laserjet_1102w.cdd
  gcp_uuid: VND3R11877
  gcp_manufacturer: Hewlett-Packard
  gcp_model: LaserJet P1102w
  gcp_setup_url: http://www8.hp.com/us/en/campaigns/wireless-printing-center/printer-setup-help.html
  gcp_support_url: http://h10025.www1.hp.com/ewfrf/wc/product?product=4110396&lc=en&cc=us&dlc=en&lang=en&cc=us
  gcp_update_url: http://h10025.www1.hp.com/ewfrf/wc/product?product=4110396&lc=en&cc=us&dlc=en&lang=en&cc=us
  gcp_firmware: '20130703'
lime:
  gcp_xmpp_jid: 3e0163e6a4802ba77c29d73410aad929@cloudprint.googleusercontent.com
  gcp_confirmation_url: https://www.google.com/cloudprint/regconfirmpage?printername=gcp_lime_printer&email=dsanderson77@gmail.com&dpi=300&pagesize=215900,279400
  gcp_owner_email: dsanderson77@gmail.com
  gcp_printer_name: gcp_lime_printer
  gcp_printerid: 8231517c-716d-4b0a-f721-83fdbe52a05d
  gcp_access_token: ya29.UgA-fXhCHp0ZiR0AAADbQqXfRA-ks9CK2POGZA8yYF2a1vhEQa4G4_QSltFK_g
  gcp_refresh_token: 1/NjwUJyyrebUIXsvl1mvqDmKCr-VtZfYR3pPusRPkLH0
  gcp_token_type: Bearer
  gcp_token_expiry_time: 2014-07-30 10:27:22.592090444 -07:00
  is_active: false
  virgin_access: false
  printer_id: 0
  item: lime
  cups_alias: laserjet_1102w
  capability_ppd: /etc/cups/ppd/laserjet_1102w.ppd
  capability_cdd: /etc/cups/cdd/laserjet_1102w.cdd
  gcp_uuid: VND3R11877
  gcp_manufacturer: Hewlett-Packard
  gcp_model: LaserJet P1102w
  gcp_setup_url: http://www8.hp.com/us/en/campaigns/wireless-printing-center/printer-setup-help.html
  gcp_support_url: http://h10025.www1.hp.com/ewfrf/wc/product?product=4110396&lc=en&cc=us&dlc=en&lang=en&cc=us
  gcp_update_url: http://h10025.www1.hp.com/ewfrf/wc/product?product=4110396&lc=en&cc=us&dlc=en&lang=en&cc=us
  gcp_firmware: '20130703'
